### ISSUE TITLE
请问资源文件该如何引入？

### ISSUE THREAD

**Issue by usercao** [chenqingspring/vue-lottie#10]
![image](https://user-images.githubusercontent.com/13760476/40294071-8bcc5604-5d06-11e8-8ec0-28145986dde8.png)
这是放置的目录路径
```JavaScript
import * as PercentFour from '@/assets/QRcode/data.json'
```
这样导入后图片资源加载不出来
使用了vue全家桶

**Comment by chenqingspring** [comment]
Please check the demo for usage :)

**Comment by mirari** [comment]
demo的示例是纯svg的，完美规避了如何引入图片资源的用法

**Comment by usercao** [comment]
@mirari 请查看问题里面的我的另外一个回答，我已经测试成功了

**Comment by mirari** [comment]
我也是这么处理的，但感觉不够优雅

**Comment by usercao** [comment]
有时间可以fork一个弄优雅点，没时间还是先把业务代码写完吧哈哈哈
