### ISSUE TITLE
Fire animation after scroll into viewport

### ISSUE THREAD

**Issue by jamesgillispie** [chenqingspring/vue-lottie#24]
Been struggling to get this to work, any chance you could suggest a way?

```this.anim.play();```

error: Cannot pass anim object into function. Using this code

```    mounted(){
      function navSlide(anim) {
        var topthis = $('.animate-this').offset();
        var $window = $(window);
        if ( $window.scrollTop() >= topthis.top) {
          this.anim.play();
        }
      }

      navSlide();
```

error: ```vue.esm.js:591 [Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'anim' of undefined"```

**Comment by innovaweb-dev** [comment]
Hi @jamesgillispie 
You must just add `anim` in your component's data.

**Comment by Jamesbillard12** [comment]
You could use a interception observer.( https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API ). There is a polyfill on npm (https://www.npmjs.com/package/intersection-observer) for browsers that don't currently support this API.

**Comment by jamesgillispie** [comment]
@Jamesbillard12 thanks for pointing me in right direction, installed https://github.com/Akryum/vue-observe-visibility, and ```     visibilityChanged (isVisible, entry) {
        this.isVisible = isVisible
        // console.log(entry);
        if (entry.isIntersecting) {
          this.anim.play();
        }
      }``` works
