### ISSUE TITLE
What is Lottie.vue in example code?

### ISSUE THREAD

**Issue by SteveLewisZA** [chenqingspring/vue-lottie#46]
The example code references Lottie.vue, what is this? What would go in that component? I'm a little confused

**Comment by jackrsantana** [comment]
I also have this doubt. Did you find any solution?

**Comment by SteveLewisZA** [comment]
> I also have this doubt. Did you find any solution?

Yes I found that this component file (Lottie.vue) is actually in the the vue-lottie folder in node_modules, I just copied it out of there and placed with my other components then linked to it... No idea if that's what officially needs to be done or why there is no mention of it in the docs though...
