### ISSUE TITLE
Vue should be peerDependency

### ISSUE THREAD

**Issue by adriaanbaelus** [chenqingspring/vue-lottie#7]
Hey, thanks for the work, vue-lottie is really cool!
I think you want vue defined as a peerDependency instead of a straight dependency?
Currently, vue-lottie will install its own version of vue. I think it should be up to the consumer of vue-lottie to define which version of vue to use?

For example, I have a project that uses nuxt. We got a runtime error because vue-server-renderer is at version 2.5.13 (defined by nuxt) while vue is at version 2.5.16 (defined by vue-lottie). All of that can be fixed by me, but it wouldn't have been a problem in the first place if you defined vue as a peerDependency.

**Comment by chenqingspring** [comment]
Thanks for point it out, I'll fix it in next release :)

**Comment by chenqingspring** [comment]
v0.2.0 is released

**Comment by 289373410** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
